//
// Created by Aimen Fahmi on 2020-04-06.
//

#ifndef E_COMMERCE_STORE_COMMUNICATIONPROTOCOL_H
#define E_COMMERCE_STORE_COMMUNICATIONPROTOCOL_H

/** Acknowledgments **/

#define ITEM_COUNT_INCREASE_SUCCESS "1"
#define ITEM_BUYING_SUCCESS "2"
#define ITEM_WRITING_SUCCESS "3"

#define ITEM_COUNT_INCREASE_FAILURE "-1"
#define ITEM_BUYING_FAILURE "-2"
#define ITEM_WRITING_FAILURE "-3"
#define ITEM_DOESNT_EXIST "-5"

#define PORT 5000

#define NETWORK_FAILURE -4

#endif //E_COMMERCE_STORE_COMMUNICATIONPROTOCOL_H
